version: '2'
services:
  mongo:
    image: mongo:4.4.1
    ports:
      - 27017:27017
    entrypoint: ['/usr/bin/mongod', '--bind_ip_all', '--replSet', 'rs0']
  mongo_init_replicaset:
    image: mongo:4.4.1
    entrypoint:
      [
        '/bin/sh',
        '-c',
        'sleep 3 && mongo localhost:27017 --eval ''rs.initiate({_id : "rs0",members: [{_id : 0, host: "localhost:27017"}]})''',
      ]
    depends_on:
      - mongo
    network_mode: host
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
