module.exports = {
  ORDER: {
    ascending: 1,
    descending: -1,
  },
  MONGO_FIELD: {
    updateAt: '_updated_at',
    createdAt: '_created_at',
  },
  STATUS: {
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
    DELETED: 'DELETED',
    UNPUBLISHED: 'UNPUBLISHED',
    PUBLISHED: 'PUBLISHED',
  },
  SALON_STATUS: {
    ACTIVE: 'ACTIVE',
    DELETED: 'DELETED',
  },
  USER_STATUS: {
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
    INVITED: 'INVITED',
    DELETED: 'DELETED',
  },
  USER_ROLE: {
    SALON_OPERATOR: 'OPERATOR',
    ADMIN: 'ADMIN',
    STYLIST: 'STYLIST',
    CUSTOMER: 'CUSTOMER',
  },
  BOOKING_STATUS: {
    REQUESTED: 'REQUESTED',
    CONFIRMED: 'CONFIRMED',
    CANCELED_OPERATOR: 'CANCELED_OPERATOR',
    CANCELED_CUSTOMER: 'CANCELED_CUSTOMER',
    CANCELED_STYLIST: 'CANCELED_STYLIST',
    CANCELED_WITH_FEE: 'CANCELED_WITH_FEE',
    CANCELED_AUTO: 'CANCELED_AUTO',
    COMPLETED: 'COMPLETED',
    NOT_ARRIVED: 'NOT_ARRIVED',
  },
  BOOKING_STATUS_EXTEND: {
    REQUESTED: 'REQUESTED',
    CONFIRMED: 'CONFIRMED',
    REQUESTED_CANCELED_OPERATOR: 'REQUESTED_CANCELED_OPERATOR',
    REQUESTED_CANCELED_CUSTOMER: 'REQUESTED_CANCELED_CUSTOMER',
    REQUESTED_CANCELED_STYLIST: 'REQUESTED_CANCELED_STYLIST',
    CONFIRMED_CANCELED_OPERATOR: 'CONFIRMED_CANCELED_OPERATOR',
    CONFIRMED_CANCELED_CUSTOMER: 'CONFIRMED_CANCELED_CUSTOMER',
    CONFIRMED_CANCELED_STYLIST: 'CONFIRMED_CANCELED_STYLIST',
    CANCELED_WITH_FEE: 'CANCELED_WITH_FEE',
    CANCELED_AUTO: 'CANCELED_AUTO',
    COMPLETED: 'COMPLETED',
    NOT_ARRIVED: 'NOT_ARRIVED',
  },

  BOOKING_STATUS_EXTEND_JP: {
    REQUESTED: '予約リクエスト',
    CONFIRMED: '予約確定',
    REQUESTED_CANCELED_OPERATOR: '予約リクエスト・サロンキャンセル',
    REQUESTED_CANCELED_CUSTOMER: '予約リクエスト・カスタマーキャンセル',
    REQUESTED_CANCELED_STYLIST: '予約リクエスト・スタイリストキャンセル',
    CONFIRMED_CANCELED_OPERATOR: '予約確定・サロンキャンセル',
    CONFIRMED_CANCELED_CUSTOMER: '予約確定・カスタマーキャンセル',
    CONFIRMED_CANCELED_STYLIST: '予約確定・スタイリストキャンセル',
    CANCELED_WITH_FEE: 'キャンセル料',
    CANCELED_AUTO: '自動キャンセル',
    COMPLETED: 'サービス完了',
    NOT_ARRIVED: '不来店キャンセル',
  },
  PAYMENT_STATUS: {
    PENDING: 'PENDING',
    IN_PROGRESS: 'IN_PROGRESS',
    CANCELED: 'CANCELED',
    FAILED: 'FAILED',
    SUCCEEDED: 'SUCCEEDED',
    OTHER: 'OTHER',
  },
  BOOKING_STATUS_JP: {
    REQUESTED: '予約リクエスト',
    CONFIRMED: '予約確定',
    CANCELED_OPERATOR: 'サロンキャンセル',
    CANCELED_CUSTOMER: 'カスタマーキャンセル',
    CANCELED_STYLIST: 'スタイリストキャンセル',
    CANCELED_WITH_FEE: 'キャンセル料',
    CANCELED_AUTO: '自動キャンセル',
    COMPLETED: 'サービス完了',
    NOT_ARRIVED: '不来店キャンセル',
  },
  PAYMENT_STATUS_JP: {
    PENDING: '保留中',
    IN_PROGRESS: '処理中',
    CANCELED: 'キャンセル',
    FAILED: '決済エラー',
    SUCCEEDED: '決済完了',
    OTHER: 'その他',
  },
  PRODUCT_TYPE: {
    USER: 'USER',
    SALON: 'SALON',
  },
  IMAGE_TYPE: {
    AVATAR: 'AVATAR',
  },
  MESSAGE: {
    LOGIN_REQUIRED: 'Login required!',
    INVALID_USER: 'Invalid user!',
    PERMISSION_ERROR: 'Permission error!',
    OBJECT_NOT_FOUND: 'Object not found!',
    INVALID_AVATAR: 'Invalid avatar!',
    EMAIL_DOES_NOT_EXIST: 'Email does not exist!',
    INVALID_PARAMS: 'Invalid params!',
    INVALID_PHONE: 'Phone number must be 10 digit number',
  },
  REGEX: {
    MONTHDATE: /^(0[1-9]|1[0-2])\/(0[1-9]|[12]\d|3[01])$/, // MM/DD
    YEAR_MONTH_DAY: /^([0-9]{4})\/(0[1-9]|1[0-2])\/(0[1-9]|[12]\d|3[01])$/, // YYYY/MM/DD
    DATE: /^([0-9]{4})-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])$/, // YYYY-MM-DD
    HOURSPAN: /^(0[0-9]|1[0-9]|2[0-3]):([0-5][0-9])-(0[0-9]|1[0-9]|2[0-3]):([0-5][0-9])$/,
    HOUR_MINUTE: /^(0[0-9]|1[0-9]|2[0-3]):([0-5][0-9])$/,
    DATE_TIME: /^\d{4}-[01]\d-[0-3]\dT[0-2]\d:[0-5]\d:00.000([+-][0-2]\d:[0-5]\d|Z)$/,
    DATE_ISO: /^\d{4}-[01]\d-[0-3]\dT[0-2]\d:[0-5]\d:[0-5]\d.\d{3}([+-][0-2]\d:[0-5]\d|Z)$/,
    POSTALCODE: /^\d{3}-\d{4}$/,
    NOT_WHITESPACE: /^\S*$/,
    SALON_NAME: /^[^`~!@#$%^&*()+={}\[\]|\\:;"'<>,/?]+$/,
    PHONE: /\d{10,13}/,
    EMAIL: /^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$/,
  },
  THUMBNAIL_SIZE: {
    SALON: {
      thumbLarge: {
        width: 800,
        height: 800,
      },
      thumbMedium: {
        width: 600,
        height: 600,
      },
      thumbSmall: {
        width: 250,
        height: 250,
      },
    },
    DEFAULT: {
      thumbLarge: {
        width: 800,
        height: 800,
      },
      thumbMedium: {
        width: 600,
        height: 600,
      },
      thumbSmall: {
        width: 250,
        height: 250,
      },
    },
    BANNER: {
      thumbLarge: {
        width: 1108,
        height: 480,
      },
      thumbMedium: {
        width: 686,
        height: 298,
      },
      thumbSmall: {
        width: 343,
        height: 149,
      },
    },
  },
  PAGING_ORDER: {
    ASC: 'ascending',
    DESC: 'descending',
  },
  FACE_SHAPES: ['丸型', '卵型', '四角', '逆三角', 'ベース'],
  GENDER: ['男性', '女性', 'その他'],
  PAYMENT_METHOD: ['CREDIT_CARD'],
  DEFAULT_TIMEZONE: 'Asia/Tokyo',
  ROLES: ['OPERATOR', 'ADMIN', 'STYLIST', 'CUSTOMER'],
  SLOT_INTERVAL: 30,
  MINUTES_PER_HOUR: 60,
  BOOKING_STATUSES: [
    'REQUESTED',
    'CONFIRMED',
    'CANCELED_OPERATOR',
    'CANCELED_CUSTOMER',
    'CANCELED_STYLIST',
    'CANCELED_WITH_FEE',
    'CANCELED_AUTO',
    'COMPLETED',
    'NOT_ARRIVED',
  ],
  PAYMENT_STATUSES: ['PENDING', 'IN_PROGRESS', 'CANCELED', 'FAILED', 'SUCCEEDED', 'OTHER'],
  EMAIL_TEMPLATES: ['booking-job-soon-customer'],
  ONE_DAY_IN_MS: 86400000,
  YOPMAIL_SUFFIX: '@yopmail.com',
  CONFIRM_BOOKING_ACTION: 'confirmBooking',
  EMPTY_SALON_SCHEDULE: {
    0: {},
    1: {},
    2: {},
    3: {},
    4: {},
    5: {},
    6: {},
  },
  EMPTY_WEEKLY_SCHEDULE: {
    0: [{ startTime: '00:00', endTime: '00:00' }],
    1: [{ startTime: '00:00', endTime: '00:00' }],
    2: [{ startTime: '00:00', endTime: '00:00' }],
    3: [{ startTime: '00:00', endTime: '00:00' }],
    4: [{ startTime: '00:00', endTime: '00:00' }],
    5: [{ startTime: '00:00', endTime: '00:00' }],
    6: [{ startTime: '00:00', endTime: '00:00' }],
  },
  EMPTY_SCHEDULE: { startTime: '00:00', endTime: '00:00' },
  UNAVAILABLE_SUM_SCHEDULE: { unavailableSchedule: [{ startTime: '00:00', endTime: '23:30' }] },
  CLOSING_DATE_SUM_SCHEDULE: { isClosingDate: true },
  NOTIFICATION_TYPE: {
    RECEIVE_BOOKING: 'RECEIVE_BOOKING',
    BOOKING_CONFIRMED: 'BOOKING_CONFIRMED',
  },
  NOTIFICATION_MESSAGE: {
    RECEIVE_BOOKING: '{senderName} 様より新しい予約リクエストが届きました',
  },
  DEFAULT_HASH_PASS: '$2b$10$mrHlDsUxKMvhaRNAJogOgu5A..8sGGUj.feRIeWa.JU2Kutv7UMA6', // 123123123
  DEVICE_TYPE: {
    iOS: 'ios',
    ANDROID: 'android',
  },
  NOTIFICATION_TEMPLATES: {
    BOOKING_REQUESTED_BY_CUSTOMER: 'BOOKING_REQUESTED_BY_CUSTOMER',
    REQUESTED_BOOKING_CANCELED_BY_CUSTOMER_FOR_CUSTOMER: 'REQUESTED_BOOKING_CANCELED_BY_CUSTOMER_FOR_CUSTOMER',
    CONFIRMED_BOOKING_CANCELED_BY_CUSTOMER_FOR_CUSTOMER: 'CONFIRMED_BOOKING_CANCELED_BY_CUSTOMER_FOR_CUSTOMER',
    REQUESTED_BOOKING_CANCELED_BY_CUSTOMER_FOR_STYLIST: 'REQUESTED_BOOKING_CANCELED_BY_CUSTOMER_FOR_STYLIST',
    CONFIRMED_BOOKING_CANCELED_BY_CUSTOMER_FOR_STYLIST: 'CONFIRMED_BOOKING_CANCELED_BY_CUSTOMER_FOR_STYLIST',
    REQUESTED_BOOKING_CANCELED_BY_STYLIST_FOR_CUSTOMER: 'REQUESTED_BOOKING_CANCELED_BY_STYLIST_FOR_CUSTOMER',
    REQUESTED_BOOKING_CANCELED_BY_STYLIST_FOR_STYLIST: 'REQUESTED_BOOKING_CANCELED_BY_STYLIST_FOR_STYLIST',
    CONFIRMED_BOOKING_CANCELED_BY_STYLIST_FOR_CUSTOMER: 'CONFIRMED_BOOKING_CANCELED_BY_STYLIST_FOR_CUSTOMER',
    CONFIRMED_BOOKING_CANCELED_BY_STYLIST_FOR_STYLIST: 'CONFIRMED_BOOKING_CANCELED_BY_STYLIST_FOR_STYLIST',
    BOOKING_CANCELED_BY_SALON_FOR_CUSTOMER: 'BOOKING_CANCELED_BY_SALON_FOR_CUSTOMER',
    BOOKING_CANCELED_BY_SALON_FOR_STYLIST: 'BOOKING_CANCELED_BY_SALON_FOR_STYLIST',
    BOOKING_CANCELED_BY_SYSTEM_FOR_CUSTOMER: 'BOOKING_CANCELED_BY_SYSTEM_FOR_CUSTOMER',
    BOOKING_CANCELED_BY_SYSTEM_FOR_STYLIST: 'BOOKING_CANCELED_BY_SYSTEM_FOR_STYLIST',
    BOOKING_CONFIRMED_BY_STYLIST: 'BOOKING_CONFIRMED_BY_STYLIST',
    BOOKING_CONFIRMED_BY_SALON: 'BOOKING_CONFIRMED_BY_SALON',
    PAYMENT_COMPLETED_FOR_STYLIST: 'PAYMENT_COMPLETED_FOR_STYLIST',
    PAYMENT_COMPLETED_FOR_CUSTOMER: 'PAYMENT_COMPLETED_FOR_CUSTOMER',
    PAYMENT_ERROR: 'PAYMENT_ERROR',
    REVIEWED_BY_CUSTOMER_FOR_STYLIST: 'REVIEWED_BY_CUSTOMER_FOR_STYLIST',
    POST_CHANGE_TO_UNPUBLISHED_BY_CHANGE_MENU: 'POST_CHANGE_TO_UNPUBLISHED_BY_CHANGE_MENU',
  },
  STYLIST_APP_SCREENS: {
    BOOKING_DETAIL_SCREEN: 'BookingDetail',
    POST_LIST: 'PostList',
  },
  CSV_BOOKING_HEADER: {
    createdAt: '受付日(予約作成日)',
    objectId: '予約ID',
    stylistFullName: 'スタイリスト名',
    customerFullName: '顧客名',
    customerGender: '顧客性別',
    menusName: 'メニュー名',
    serviceDateTime: 'サービス提供日(施術日)',
    totalPrice: '総額',
    bookingStatus: '予約状況',
    paymentStatus: '支払状況',
    paymentDate: '支払確定日',
  },
  CSV_BOOKING_HEADER_ADMIN: {
    objectId: '予約ID',
    'salon.objectId': 'サロンID',
    'salon.salonName': 'サロン名',
    'stylist.fullName': 'スタイリスト名',
    'stylist.objectId': 'スタイリストID',
    'customer.fullName': 'お客様名',
    'customer.objectId': 'お客様ID',
    createdAt: '予約作成日',
    serviceDateTime: 'サービス日時',
    originalPrice: '合計金額',
    bookingStatusExtend: '予約ステータス',
    paymentStatus: '請求ステータス',
    coupon: 'クーポン値引',
  },
  CSV_SALON_HEADER: {
    objectId: 'ID',
    createdAt: '作成日',
    salonName: 'サロン名',
    salonNameKatakana: 'サロン名のフリガナ',
    salonStaffsNumber: 'スタッフ数',
    salonEmail: 'メールアドレス',
  },
  CSV_CUSTOMER_HEADER: {
    objectId: 'ID',
    createdAt: '作成日',
    fullName: 'お客様名',
    phoneticFullName: '名前 (フリガナ)',
    nickName: 'ニックネーム',
    phone: '電話番号',
    email: 'メールアドレス',
    gender: '性別',
    birthDate: '生年月日',
  },
  CSV_PAYOUT_HEADER: {
    objectId: '売上ID',
    holdingCompanyName: '所属グループ',
    salonName: 'サロン名',
    email: 'メールアドレス',
    totalSales: 'サロン売上額（税込）',
    commission: '合計マージン',
    subtotal: '小計',
    transferFee: '振込手数料',
    transferAmount: '振込金額',
    status: '振込ステータス',
  },
  CSV_PAYOUT_DETAIL_HEADER: {
    objectId: '予約ID',
    stylistName: 'スタイリスト名',
    email: 'メールアドレス',
    totalPrice: '売上額（税込）',
    commission: 'マッチング手数料',
    subtotal: '合計',
    paymentDate: '決済完了日時',
    serviceDateTime: 'サービス日',
    bookingStatusExtend: '予約ステータス',
  },
  DATE_TIME_FORMAT: 'YYYY/MM/DD HH:mm',
  EMPTY_ISO_STRING: '999999999999999999999999',
  EVENTS: {
    CANCEL_BOOKING: 'CANCEL_BOOKING',
    FINISH_BOOKING: 'FINISH_BOOKING',
    CUSTOMER_CHANGE_PROFILE: 'CUSTOMER_CHANGE_PROFILE',
    STYLIST_CHANGE_PROFILE: 'STYLIST_CHANGE_PROFILE',
    SALON_CHANGE_PROFILE: 'SALON_CHANGE_PROFILE',
    DELETED_STYLIST: 'DELETED_STYLIST',
    CUSTOMER_VERIFY_EMAIL: 'CUSTOMER_VERIFY_EMAIL',
    STYLIST_SET_FIRST_PASSWORD: 'STYLIST_SET_FIRST_PASSWORD',
    DELETED_CUSTOMER: 'DELETED_CUSTOMER',
    DELETED_SALON: 'DELETED_SALON',
    PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
    CREATE_POST: 'CREATE_POST',
    EXTERNAL_CREATE_POST: 'EXTERNAL_CREATE_POST',
    CHANGE_POST_INFO: 'CHANGE_POST_INFO',
    EXTERNAL_CHANGE_POST_INFO: 'EXTERNAL_CHANGE_POST_INFO',
  },
  REASON_DELETE_ACCOUNT: [
    {
      id: 'ZCLUDQTM9X',
      text: '予約が入らなかった',
      hasExtraInput: false,
      role: 'STYLIST',
    },
    {
      id: 'd6o5tJN8Tr',
      text: '手数料が高かった',
      hasExtraInput: false,
      role: 'STYLIST',
    },
    {
      id: 'YwtuhRnj7n',
      text: '求めているサービスがなかった',
      hasExtraInput: false,
      role: 'STYLIST',
    },
    {
      id: 'sRkcSJw71x',
      text: '通知や広告が多かった',
      hasExtraInput: false,
      role: 'STYLIST',
    },
    {
      id: 'nLBsPgWUY1',
      text: '操作方法がわかりづらかった',
      hasExtraInput: false,
      role: 'STYLIST',
    },
    {
      id: 'fSbwkByVFP',
      text: 'セキュリティーに不安があった',
      hasExtraInput: false,
      role: 'STYLIST',
    },
    {
      id: 'JDPSo8eXvI',
      text: '使う頻度が減った',
      hasExtraInput: false,
      role: 'STYLIST',
    },
    {
      id: 'a4dYt4ZA82',
      text: '他のサービスを利用したい',
      hasExtraInput: false,
      role: 'STYLIST',
    },
    {
      id: 'Ve993hByS4',
      text: 'その他',
      hasExtraInput: true,
      role: 'STYLIST',
    },
    {
      id: '16o5tJN8Tr',
      text: '予約したいスタイリストがいなかった',
      hasExtraInput: false,
      role: 'CUSTOMER',
    },
    {
      id: '2wtuhRnj7n',
      text: '求めているサービスがなかった',
      hasExtraInput: false,
      role: 'CUSTOMER',
    },
    {
      id: '3RkcSJw71x',
      text: '通知や広告が多かった',
      hasExtraInput: false,
      role: 'CUSTOMER',
    },
    {
      id: '4LBsPgWUY1',
      text: '操作方法がわかりづらかった',
      hasExtraInput: false,
      role: 'CUSTOMER',
    },
    {
      id: '5SbwkByVFP',
      text: 'セキュリティーに不安があった',
      hasExtraInput: false,
      role: 'CUSTOMER',
    },
    {
      id: '6DPSo8eXvI',
      text: '使う頻度が減った',
      hasExtraInput: false,
      role: 'CUSTOMER',
    },
    {
      id: '74dYt4ZA82',
      text: '他のサービスを利用したい',
      hasExtraInput: false,
      role: 'CUSTOMER',
    },
    {
      id: '8e993hByS4',
      text: 'その他',
      hasExtraInput: true,
      role: 'CUSTOMER',
    },
  ],

  DEFAULT_MAX_CONFIRM_BOOKING: 1,
  DEFAULT_CLEARED_FIELDS: {
    SALON: [
      'status',
      'deletedAt',
      'salonEmail',
      'salonDirection',
      'salonName',
      'slug',
      'phone',
      'salonNote',
      'salonNameKatakana',
      'salonCatchphrase',
      'salonAddress1',
      'salonAddress2',
      'salonAddress3',
      'salonAddress4',
    ],
    STYLIST: [
      'userStatus',
      'firstName',
      'lastName',
      'fullName',
      'phoneticFirstName',
      'phoneticLastName',
      'phoneticFullName',
      'nickName',
      'gender',
      'stylistEmail',
      'phone',
      'stylistSNS',
      'slug',
      'profileImages',
    ],
    CUSTOMER: [
      'userStatus',
      'firstName',
      'lastName',
      'fullName',
      'phoneticFirstName',
      'phoneticLastName',
      'phoneticFullName',
      'nickName',
      'gender',
      'email',
      'profileImages',
      'birthDate',
    ],
  },
  RECOMMENDATION_FILLTER: ['contributorId', 'receiverId'],
  TYPE_BANK_ACCOUNT: {
    CHECKING_ACCOUNT: 'CHECKING_ACCOUNT',
    SAVING_ACCOUNT: 'SAVING_ACCOUNT',
  },
  DEPOSIST_PAYMENT_STATUS: {
    PENDING: 'PENDING',
    IN_PROCCESS: 'IN_PROCCESS',
    COMPLETED: 'COMPLETED',
  },
  PAYOUT_TRANSFER_STATUS: {
    PROCESS: 'PROCESS',
    DELETED: 'DELETED',
    DONE: 'DONE',
  },
  EARNINGS_PAYOUT_STATUS: {
    PENDING: 'pending',
    SCHEDULED: 'scheduled',
    CANCELED: 'canceled',
    COMPLETED: 'completed',
    FAILED: 'failed',
    REVERTED: 'reverted',
  },
  MAX_TOP_STYLIST: 10,
  MAX_STYLIST_CONTRIBUTOR: 3,
  ADMIN_EMAIL: process.env.ADMIN_EMAIL || 'support@hairlie.jp',

  PLATFORM: {
    WEB: 'web',
    MOBILE: 'mobile',
  },
  MAX_PRESS_POST_FOR_STYLIST: 2,
  PRESS_TYPE: {
    DEFAULT: 'DEFAULT',
    SELECTION: 'SELECTION',
  },
};
