module.exports = {
  SALON: [
    'createdAt',
    'salonName',
    'slug',
    'salonNameKatakana',
    'salonCatchphrase',
    'salonImage',
    'phone',
    'postalCode',
    'salonAddress1',
    'salonAddress2',
    'salonAddress3',
    'salonAddress4',
    'salonDirection',
    'salonHolidays',
    'salonSeatsNumber',
    'salonSNS',
    'salonEmail',
    'salonStaffsNumber',
    'createdAt',
    'salonNote',
    'salonOtherNote',
    'salonPayments',
    'salonSchedules',
    'deletedAt',
    'status',
    'stationName',
    'distanceNearestStation',
    'holdingCompanny',
  ],
  SALON_CSV: ['objectId', 'createdAt', 'salonName', 'salonNameKatakana', 'salonEmail', 'salonStaffsNumber'],
  SALON_HOLDING_COMPANY: [
    'objectId',
    'salonName',
    'salonNameKatakana',
    'salonImage',
    'salonImage.thumbLarge',
    'salonImage.thumbSmall',
    'salonImage.file',
    'holdingCompany',
  ],
  CUSTOMER_CSV: [
    'objectId',
    'createdAt',
    'fullName',
    'phoneticFullName',
    'nickName',
    'phone',
    'email',
    'gender',
    'birthDate',
  ],
  CLOSING_DATE: ['startDate', 'endDate', 'note'],
  CATEGORY: ['name', 'status'],
  MENU: [
    'name',
    'amount',
    'description',
    'category',
    'category.name',
    'category.status',
    'salon',
    'assignedStylistIds',
    'duration',
    'status',
  ],
  STYLIST: [
    'salon',
    'salon.salonName',
    'salon.slug',
    'firstName',
    'lastName',
    'fullName',
    'nickName',
    'slug',
    'profileImages',
    'profileText',
    'stylistSNS',
    'gender',
    'status',
    'generalScore',
    'styleScore',
    'serviceScore',
    'reviewCount',
    'userStatus',
    'newEmail',
    'requestDeletingAccount',
    'userStatus',
    'deletedAt',
    'isOfficial',
    'profile',
    'maxConfirmedBookingCount',
  ],
  PRODUCT: ['images', 'name', 'price', 'type', 'description', 'status', 'salon', 'url'],
  POST: [
    'stylist',
    'stylist.fullName',
    'stylist.nickName',
    'stylist.slug',
    'stylist.profileImages',
    'stylist.generalScore',
    'stylist.styleScore',
    'stylist.serviceScore',
    'stylist.reviewCount',
    'stylist.isOfficial',
    'stylist.status',
    'images',
    'description',
    'tags',
    'menus',
    'products',
    'faceShapes',
    'totalPrice',
    'status',
    'salon',
    'salon.salonName',
    'salon.slug',
    'favoriteCustomers',
  ],
  FAVORITE_POST: {
    _id: 0,
    objectId: '$_id',
    'stylist.objectId': 1,
    images: 1,
    createdAt: { $dateToString: { date: '$_created_at' } },
    isFavorite: 1,
    totalPrice: 1,
    faceShapes: 1,
    status: 1,
  },
  IMAGE: ['thumbSmall.url', 'thumbMedium.url', 'thumbLarge.url', 'file.url'],
  CUSTOMER: [
    'firstName',
    'lastName',
    'fullName',
    'phoneticFirstName',
    'phoneticLastName',
    'phoneticFullName',
    'nickName',
    //'username',
    'email',
    'gender',
    'birthDate',
    'profileImages',
    'phone',
    'paymentMethod',
    'isCompletedProfile',
    'requestDeletingAccount',
    'userStatus',
    'deletedAt',
  ],
  BOOKING: [
    'stylist',
    'stylist.nickName',
    'stylist.slug',
    'stylist.profileImages',
    'stylist.fullName',
    'stylist.isOfficial',
    'salon',
    'salon.salonName',
    'salon.slug',
    'salon.postalCode',
    'salon.salonAddress3',
    'salon.salonAddress4',
    'customer',
    'customer.profileImages',
    'customer.nickName',
    'customer.gender',
    'customer.phone',
    'customer.phoneticFullName',
    'customer.birthDate',
    'customer.fullName',
    'menus',
    'menus.amount',
    'menus.duration',
    'menus.name',
    'serviceDateTime',
    'totalDuration',
    'totalPrice',
    'cardInfo',
    'cancelNote',
    'bookingStatus',
    'paymentStatus',
    'paymentNote',
    'total',
    'isReviewed',
    'originalPrice',
    'visitedSalon',
    'customerNote',
  ],

  BOOKING_ADMIN: [
    'objectId',
    'stylist',
    'stylist.objectId',
    'stylist.nickName',
    'stylist.profileImages',
    'stylist.fullName',
    'stylist.isOfficial',
    'salon',
    'salon.objectId',
    'salon.salonName',
    'salon.salonImage',
    'salon.salonAddress3',
    'salon.salonAddress4',
    'customer',
    'customer.objectId',
    'customer.profileImages',
    'customer.nickName',
    'customer.phoneticFullName',
    'customer.fullName',
    'totalDuration',
    'totalPrice',
    'cancelNote',
    'bookingStatus',
    'paymentStatus',
    'paymentNote',
    'total',
    'isReviewed',
    'originalPrice',
    'visitedSalon',
    'customerNote',
    'coupon.couponCode',
    'coupon.transaction',
    'lastBookingStatus',
    'serviceDateTime',
    'bookingStatusExtend',
    'createdAt',
  ],
  PAYMENT: ['status', 'request', 'createdAt'],
  NOTIFICATION: [
    'data',
    'isRead',
    'isDeleted',
    'senderCustomer',
    'senderCustomer.nickName',
    'senderCustomer.profileImages',
    'senderCustomer.fullName',
    'booking',
  ],
  APP_NOTIFICATION: ['data', 'isRead', 'isDeleted', 'title', 'inAppTitle', 'body'],
  CONTACT_US: ['name', 'email', 'phoneNumber', 'contents', 'otherInfos'],
  PREFECTURE: ['value', 'nameEn', 'nameJp'],
  REVIEW: ['generalScore', 'styleScore', 'serviceScore', 'comment', 'customer', 'customer.nickName'],
  REVIEW_ADMIN: {
    _id: 0,
    objectId: '$_id',
    'customer.objectId': 1,
    'customer.nickName': 1,
    'customer.fullName': 1,
    'customer.profileImages': 1,
    comment: 1,
    'stylist.objectId': 1,
    'stylist.nickName': 1,
    'stylist.fullName': 1,
    'stylist.profileImages': 1,
    'stylist.isOfficial': 1,
    'salon.objectId': 1,
    'salon.salonName': 1,
    'salon.salonNameKatakana': 1,
    bookingId: 1,
    generalScore: 1,
    styleScore: 1,
    serviceScore: 1,
    createdAt: { $dateToString: { date: '$_created_at' } },
  },
  FAVORITED_STYLIST: {
    _id: 0,
    'stylist.objectId': 1,
    'stylist.nickName': 1,
    'stylist.fullName': 1,
    'stylist.profileImages': 1,
    'stylist.isOfficial': 1,
    'salon.objectId': 1,
    'salon.salonName': 1,
    'salon.salonNameKatakana': 1,
    createdAt: { $dateToString: { date: '$_created_at' } },
  },
  RECOMMENDATION_STYLIST: {
    _id: 0,
    objectId: '$_id',
    'contributor.objectId': 1,
    'contributor.nickName': 1,
    'contributor.fullName': 1,
    'contributor.profileImages': 1,
    'contributor.catchPhrase': 1,
    'contributor.reviewCount': 1,
    'contributor.generalScore': 1,
    'contributor.isOfficial': 1,
    'salonReceiver.objectId': 1,
    'salonReceiver.salonName': 1,
    'salonReceiver.salonNameKatakana': 1,
    'salonReceiver.stationName': 1,
    'salonReceiver.distanceNearestStation': 1,
    'receiver.objectId': 1,
    'receiver.nickName': 1,
    'receiver.fullName': 1,
    'receiver.profileImages': 1,
    'receiver.catchPhrase': 1,
    'receiver.reviewCount': 1,
    'receiver.isOfficial': 1,
    'receiver.generalScore': 1,
    'salonContributor.objectId': 1,
    'salonContributor.salonName': 1,
    'salonContributor.salonNameKatakana': 1,
    'salonContributor.stationName': 1,
    'salonContributor.distanceNearestStation': 1,
    title: 1,
    content: 1,
    createdAt: { $dateToString: { date: '$_created_at' } },
    updateAt: { $dateToString: { date: '$_updated_at' } },
  },
  REVIEW_ADMIN_SEARCH_KEY: ['customer.searching', 'salon.searching', 'stylist.searching'],
  BANNER: ['sortOrder', 'status', 'image.file', 'image.thumbSmall', 'image.thumbMedium', 'image.thumbLarge'],
  HOLDING_COMPANY: ['name'],
  HASHTAG: ['name', 'platform', 'sortOrder', 'image.file', 'image.thumbSmall', 'image.thumbMedium', 'image.thumbLarge'],
  STYLIST_ADMIN: {
    _id: 0,
    objectId: '$_id',
    nickName: 1,
    fullName: 1,
    isOfficial: 1,
    profileImages: 1,
    createdAt: { $dateToString: { date: '$_created_at' } },
  },
  TOP_STYLIST: {
    _id: 0,
    objectId: '$_id',
    nickName: 1,
    fullName: 1,
    gender: 1,
    status: 1,
    stylistEmail: 1,
    profileImages: 1,
    isOfficial: 1,
    salonId: { $last: { $split: ['$_p_salon', `Salon$`] } },
    sortOrder: '$topStylist.sortOrder',
  },

  PRESS_POST: ['objectId', 'title', 'image.file', 'description', 'rank', 'detailURL', 'createAt'],
  PRESS_POST_ADMIN: {
    _id: 0,
    objectId: '$_id',
    title: 1,
    'image.file': 1,
    stylists: 1,
    detailURL: 1,
    updateAt: { $dateToString: { date: '$_updated_at' } },
  },

  PRESS_POST_DETAIL_ADMIN: [
    'objectId',
    'title',
    'image.file',
    'detailURL',
    'stylists',
    'stylists.objectId',
    'stylists.fullName',
    'stylists.nickName',
    'stylists.profileImages',
    'stylists.salon',
    'stylists.salon.objectId',
    'stylists.salon.salonName',
    'stylists.salon.salonNameKatakana',
    'stylists.salon.salonImage',
    'createAt',
  ],

  STYLIST_FOR_PRESS_POST: [
    'salon',
    'salon.objectId',
    'salon.salonName',
    'fullName',
    'nickName',
    'totalPressPost',
    'profileImages',
  ],
};
